### ISSUE TITLE
Kampanyalar Tabbar Padding

### ISSUE THREAD

**Issue by denizhacisalihoglu** [Ucurtma/ucurtma-app#250]
Kampanyalar sayfasındaki tabbar butonlarının aralıklarının açılması gerekiyor. Şu anda çok bitişik duruyor. 
![image](https://user-images.githubusercontent.com/4246313/115956258-87b26600-a504-11eb-8617-a79c54ddb7a8.png)

margin-right: 0.75rem
margin-top/bottom: 2rem değerlendirilebilir.

**Comment by enesinan** [comment]
Bu issue üzerine çalışabilir miyim?

**Comment by mustaphaturhan** [comment]
hazırladığın bu harika issue için teşekkürler @denizhacisalihoglu. @enesinan tabi ki, uçurtma projesi olarak her türlü katkıya açığız. şimdiden ellerine sağlık, kolay gelsin 👋🏻
